[[redirects]]
  from = "/cart"
  to = "https://cart-poc.netlify.app/cart"
  status = 200

[[redirects]]
  from = "/cart/*"
  to = "https://cart-poc.netlify.app/cart/:splat"
  status = 200

[[redirects]]
  from = "/checkout"
  to = "https://checkout-poc.netlify.app/checkout"
  status = 200

[[redirects]]
  from = "/checkout/*"
  to = "https://checkout-poc.netlify.app/checkout/:splat"
  status = 200

[[redirects]]
  from = "/catalog"
  to = "https://catalog-poc.netlify.app/catalog"
  status = 200

[[redirects]]
  from = "/catalog/*"
  to = "https://catalog.netlify.app/catalog/:splat"
  status = 200
